import dotenv from "dotenv/config";
import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import cssModulesPlugin from "esbuild-css-modules-plugin"
import {sassPlugin} from 'esbuild-sass-plugin'
import fse from 'fs-extra';
import chalk from 'chalk';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

console.log(`esbuild version = ${esbuild.version}`);

const prod = process.argv[2] === "production";

const DEFAULT_DROPBOX_APP_KEY = process.env.DROPBOX_APP_KEY || "";
const DEFAULT_ONEDRIVE_CLIENT_ID = process.env.ONEDRIVE_CLIENT_ID || "";
const DEFAULT_ONEDRIVE_AUTHORITY = process.env.ONEDRIVE_AUTHORITY || "";

esbuild
  .build({
    banner: {
      js: banner,
    },
    loader: {
      ".svg": "text",
      '.txt.js': 'text',
		  '.txt.css': 'text',
		  '.wasm': 'binary'
    },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "fs",
      "os",
      "tls",
      "net",
      "https",
      "http",
      "zlib",
      "child_process",
      "constants",
      // "process",
      "timers",
      '@codemirror/autocomplete',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      // ...builtins
    ],
    inject: ["./esbuild.injecthelper.mjs"],
    plugins: [cssModulesPlugin({
      inject: true
    })],
    format: "cjs",
    watch: !prod,
    target: 'esnext',
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: "main.js",
    define: {
      "process.env.DEFAULT_DROPBOX_APP_KEY": `"${DEFAULT_DROPBOX_APP_KEY}"`,
      "process.env.DEFAULT_ONEDRIVE_CLIENT_ID": `"${DEFAULT_ONEDRIVE_CLIENT_ID}"`,
      "process.env.DEFAULT_ONEDRIVE_AUTHORITY": `"${DEFAULT_ONEDRIVE_AUTHORITY}"`,
      global: "window",
      "process.env.NODE_DEBUG": `undefined`, // ugly fix
      "process.env.DEBUG": `undefined`, // ugly fix
    },
  })
  .catch(() => process.exit(1));



esbuild
  .build({
    entryPoints: [
      'src/styles/styles.js'
    ],
    plugins: [
      sassPlugin(),
      cssModulesPlugin({
        force: true,
        emitDeclarationFile: true,
        localsConvention: 'camelCaseOnly',
        namedExports: true,
        inject: false
      })
    ],
    format: "iife",
    outdir: '.',
    watch: !prod,
    minify: true,
    bundle: true, 
    keepNames: true, // 保留函数和变量的原始名称
  })
  .then(result => {
    fse.rmSync('./styles.js')
    if (result.errors?.length > 0) {
      console.log(chalk.red('bundle style failed: ', result.errors));
    } else {
      console.log(chalk.green('bundle style success'));
    }
  })
  
  