name: Bug Report
description: Fire a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you using?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - iOS (iPhone, iPad)
        - Android
    validations:
      required: true
  - type: dropdown
    id: service
    attributes:
      label: What remote cloud services are you using?
      multiple: true
      options:
        - S3
        - OneDrive for personal
        - Dropbox
        - webdav
        - others
    validations:
      required: true
  - type: input
    id: version-plugin
    attributes:
      label: Version of the plugin
      description: What version of the plugin are you running?
    validations:
      required: false
  - type: input
    id: version-obsidian
    attributes:
      label: Version of Obsidian
      description: What version of Obsidian are you running?
    validations:
      required: false
  - type: checkboxes
    id: using-password
    attributes:
      label: Using password or not
      description: Are you using password (end-to-end encryption) or not?
      options:
        - label: Yes.
          required: false
  - type: checkboxes
    id: ensure-no-sensitive-information
    attributes:
      label: Ensure no sensitive information
      description: By submitting this issue, you ensure that no sensitive information is submitted in the issue.
      options:
        - label: I ensure that no sensitive information is submitted in the issue.
          required: true
